global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Maui;
global using CommunityToolkit.Maui.Markup;
global using CommunityToolkit.Mvvm.Input;
